[package]
name = "payload-archiver"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.30"
axum = "0.6"
bytes = "1.4"
eyre = "0.6"
futures = "0.3"
serde_json = "1.0"
tokio = { version = "1.29", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
