steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/ultra-sound-relay/relay/payload-archiver",
        ".",
      ]
images: ["europe-west1-docker.pkg.dev/ultra-sound-relay/relay/payload-archiver"]
